name: sync up to codecommit

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: View Files
        run: |
          ls -ltr
      - name: Git push
        run: |
          git remote add origin https://git-codecommit.us-east-1.amazonaws.com/v1/repos/github-cc
          git remote -v
          git push origin main
