name: Sync with CodeCommit

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      run: |
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
        echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

    - name: Sync with CodeCommit
      run: |
        git remote add codecommit https://git-codecommit.us-east-1.amazonaws.com/v1/repos/github-cc
        git push codecommit HEAD:refs/heads/master
